sudo: required
services:
  - docker

before_install:
  - docker build -t mlikwarz/docker-feature -f Dockerfile.dev .

script:
  - docker run -e CI=true mlikwarz/docker-feature npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-302263087884"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"